<div class="container">
    <div class="row">
        <div class="col-6">
            <h2 class="section-title text-primary">Login</h2>
            <p>Forneça os dados de acesso para entrar.</p>

            <form class="user" method="post" action="/autenticar">
                <input type="email" id="email" name="email" placeholder="E-mail" class="form-control mb-4 shadow rounded-0">

                <input type="password" id="senha" name="senha" placeholder="Senha" class="form-control mb-4 shadow rounded-0">

                <button type="submit" value="dados" class="btn btn-primary">Entrar</button>

                <hr>

                <div>
                    <a href="#">Esqueceu a senha?</a>
                </div>

                <div>
                    <a href="#">Criar conta</a>
                </div>




          <!-- variavel que se ecisti na url ela vai existir para rodar o erro 401 -->
                <?php if ($this->view->login == 401) { ?>
                    <!-- <div class="row mt-3">
                        <span class="text text-danger">E-mail e ou senha inválido(s)</span>
                    </div> -->
                    <script>
                        swal("erro!", "login e senha validos", "error");
                    </script>
                <?php } ?>
            </form>
        </div>
    </div>
</div>